name: CI

on:
  push:
    branches: [ capacitor ]
  workflow_dispatch: # allow manual start

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.repository_owner }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: |
          python -m pip install click==8.2 bump-my-version==0.32.2
          bump-my-version bump patch --no-commit --verbose

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: |
          echo "VITE_BASE_PATH=./" > .env.local
          echo "VITE_SERVERLESS=1" >> .env.local
          npm run build
          rm .env.local

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Capacitor Sync
        working-directory: frontend
        run: npx cap sync android

      - name: Build Android App
        working-directory: frontend
        run: cd android && ./gradlew assembleDebug

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          generate_release_notes: true
          append_body: false
          files: |
            frontend/android/app/build/outputs/apk/debug/*.apk
