name: CI

on:
  push:
    branches:
      - '*'
  workflow_run:
    workflows: ["Bump version and create release"]
    types:
      - completed
  workflow_dispatch: # allow manual start

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.repository_owner }}
  REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Bump version
        run: |
          pip install bump-my-version==1.3.0
          bump-my-version bump patch --no-commit --verbose

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
 
      - name: Login to ${{ env.REGISTRY }} registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASS }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            #type=semver,pattern={{major}}.{{minor}}
            #type=semver,pattern={{major}}

      - name: Build and push docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  android-and-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Bump version
        run: |
          pip install bump-my-version==1.3.0
          bump-my-version bump patch --no-commit --verbose

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: |
          echo "VITE_BASE_PATH=/OpenNumismatWeb/dev/" > .env.local
          echo "VITE_SERVERLESS=1" >> .env.local
          npm run build
          rm .env.local

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          destination_dir: dev

      - name: Build Android
        working-directory: frontend
        run: |
          echo "VITE_BASE_PATH=./" > .env.local
          echo "VITE_PLATFORM_ANDROID=1" >> .env.local
          npm run build
          rm .env.local

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '24'

#      - name: Generate Assets
#        working-directory: frontend
#        run: npx capacitor-assets generate --android

      - name: Set Build Number
        working-directory: frontend
        run: |
          sed -i "s/versionCode [0-9]*/versionCode ${{ github.run_number }}/" android/app/build.gradle

      - name: Capacitor Sync
        working-directory: frontend
        run: npx cap sync android

      - name: Build Android App
        working-directory: frontend
        run: cd android && ./gradlew assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: frontend/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0" 

      - name: Delete old release
        run: gh release delete latest --yes --cleanup-tag || echo "Not found"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          generate_release_notes: true
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
